from pathlib import Path
import requests
import sqlite3
import pandas as pd
from selenium import webdriver
from selenium.webdriver.edge.options import Options
from selenium.webdriver.edge.service import Service
#from selenium_stealth import stealth
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException
import os
from bs4 import BeautifulSoup
from datetime import datetime

#Confiuration
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0"
}

url = "https://www.imdb.com/search/title/"

output_dir = "/output"
output_folder = os.path.join(os.getcwd(), output_dir)
if not os.path.exists(output_folder):
    os.makedirs(output_folder)

db_path = os.path.join(output_folder, "movies.db")
excel_path = os.path.join(output_folder, "movies.xlsx")

#Parameters for the page fetch function
PARAMS = {
    "title-type": "feature",
    "release_date": "",
    "user_rating": "",
    "genres": "",
    "sort": "user_rating,asc",
    "start": 1,
    "count": 50,    
}

#Fetches the page and convert into a readable html document

def fetch_page(params):
    # Set up the Selenium WebDriver with Edge options
    edge_options = Options()
    edge_options.add_argument("user-agent=MikeLsAgent")
    edge_options.add_argument("--disable-blink-features=AutomationControlled")
    edge_options.add_argument("--start-maximized")

    # Path to EdgeDriver
    driver_path = "C:/WebDriver/msedgedriver.exe" 
    service_options = Service(driver_path)
    
    # Set up driver with options
    driver = webdriver.Edge(service=service_options, options=edge_options)
    # Set up stealth mode to avoid detection
    # stealth(driver,
    #     languages=["en-US", "en"],
    #     vendor="Google Inc.",
    #     platform="Win32",
    #     webgl_vendor="Intel Inc.",
    #     renderer="Intel Iris OpenGL Engine",
    #     fix_hairline=True,
    # )

    # Create url with parameters
    driver.get(url + "?" + "&".join([f"{key}={value}" for key, value in params.items()]))

    # Use WebDriverWait to wait for the page to load (replace with a relevant element to wait for)
    try:
        WebDriverWait(driver, 10).until(
            EC.presence_of_element_located((By.CSS_SELECTOR, ".main-content"))
        )
    except TimeoutException:
        print("Timed out waiting for page to load.")
        driver.quit()
        return None

    # Get the page source after JS loads and close the driver
    html = driver.page_source
    driver.quit()

    return html

    

#Parses the html doc generated by the fetch_page function and returns a list of dictionaries containing the movie data
def parse_html(html):
    # Parse the HTML content using BeautifulSoup
    soup = BeautifulSoup(html, "html.parser")
    movies = []
    containers = soup.find_all("div", class_="lister-item mode-advanced")

    for container in containers:
        # Extract the movie title, year, rating, and genre
        header = container.find("h3", class_="lister-item-header")
        title = header.find("a").text.strip()
        year_tag = header.find("span", class_="lister-item-year").text.strip()
        year = year_tag.text.strip() if year_tag else None
        rating_tag = container.find("div", class_="inline-block ratings-imdb-rating")
        rating = float(rating_tag["data-value"]) if rating_tag else None
        genre_tag = container.find("span", class_="genre")
        genre = genre_tag.text.strip() if genre_tag else None

        # Append the movie data to the list
        movies.append({
            "title": title,
            "year": year,
            "rating": rating,
            "genre": genre,
            "scrape-date": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        })
    return movies

#Intialize a SQLite database to store the data\
def init_db(dbase_path="movies.db"):
  
    conn = sqlite3.connect(dbase_path)
    cursor = conn.cursor()
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS movies (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            title TEXT,
            year TEXT,
            rating REAL,
            genre TEXT,
            scrape_date TEXT
        )
    """)
    conn.commit()
    return conn

#Saves the movie data to the SQLite database
def save_to_db(conn, movies):
    cursor = conn.cursor()
    for movie in movies:
        cursor.execute("""
            INSERT INTO movies (title, year, rating, genre, scrape_date)
            VALUES (?, ?, ?, ?, ?)
        """, (movie["title"], movie["year"], movie["rating"], movie["genre"], movie["scrape-date"]))
    conn.commit()

#Exports the database into an excel file
def export_to_excel(conn, excel_path="movies.xlsx"):
    # selects everything from movies table and converts into an excel file
    data_frame = pd.read_sql_query("SELECT * FROM movies", conn)
    data_frame.to_excel(excel_path, index=False)

# Main function to run the scraper
def main():
    #Initialize the database and output paths
    output_dir = Path(__file__).parent / "output"
    conn = init_db(dbase_path=output_dir/"movies.db")

    #Loop through set amount of entries and fetch the data
    for start in range(1, 1000, 50):
        PARAMS["start"] = start
        html = fetch_page(PARAMS)
        with open("debug.html", "w", encoding="utf-8") as f:
            f.write(html)
        movie_list = parse_html(html)
        if not movie_list:
            print(f"No more movies found at start={start}. Stopping the scraper.")
            break
        save_to_db(conn, movie_list)
        print(f"Fetched and saved {len(movie_list)} movies from page starting at {start}.")
    
    #Export the database to an excel file
    export_to_excel(conn, excel_path=output_dir/"movies.xlsx")
    print("Exported data to movies.xlsx")
    print("Scraping completed.")

    #Close the database connection
    conn.close()

#Run the main function
if __name__ == "__main__":
    main()  




